### ISSUE TITLE
[EDIT] SHORT DESCRIPTION SECTION

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/hackclubiter.github.io#14]
In the heading for this section, increase the space between the word "Join" and "Hack" as they are appearing too close and the word "Join" looses its effectiveness. Actually the highlighted text should be a little separated from normal text so that the viewers don't miss-out on them.

Also space around the cards a little bit as they appear to be too close in the center and the sides look bland

**Comment by saswatsamal** [comment]
The Space between the words is fixed. And the space between the cards is standard, if the space will be increased then it will look odd on different devices.
