### ISSUE TITLE
[EDIT] ABOUT SECTION

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/hackclubiter.github.io#15]
Under "We at Hack Club ITER", increase the line height of the text under the mentioned subheading and change the text color for "Hack Club ITER" to make it stand out. Also add some emojis like 🚀 within the text.

Also add some graphics or a background to the section as now it looks bland from the sides

**Comment by saswatsamal** [comment]
I've added the colour to Hack Club ITER to stand out and the space between the line looks fine though.

**Comment by saswatsamal** [comment]
Fixed! :)
