### ISSUE TITLE
[DISCORD]

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/hackclubiter.github.io#24]
Upon clicking "Join our Discord" button it is showing a 404 error page. Activate the joining link.

**Comment by saswatsamal** [comment]
Hey @Saswat7101 Thanks for the issue.
Make sure to add a short detail in the title too.
I'll fix the error asap. :)

**Comment by Saswat7101** [comment]
Ok

**Comment by saswatsamal** [comment]
Fixed! :) 👍🏻
