### ISSUE TITLE
[NAVBAR] navbar covering the title of the page

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/hackclubiter.github.io#25]
With fixed navbar the headings get hidden ...... instead make the navbar sticky

![WhatsApp Image 2021-08-25 at 6 57 23 PM](https://user-images.githubusercontent.com/53933493/130799104-c62e7a9c-601a-4dfa-918e-b7118c8ae353.jpeg)

**Comment by saswatsamal** [comment]
Fixed! :)
