### ISSUE TITLE
Join us button not working

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/hackclubiter.github.io#27]
Whenever I click the Join us button in the nav bar it is redirecting to this page.

![Screenshot 2021-08-27 114152](https://user-images.githubusercontent.com/53933493/131080863-33c35471-af95-4851-962a-e3b15af1435e.png)

Also in the main page in the "Join Hack Club ITER today" section upon clicking the Join us button it is showing a 404 error page.

![Screenshot 2021-08-27 114238](https://user-images.githubusercontent.com/53933493/131080995-6e6747d6-cc68-498e-94c5-569f5f00d666.png)
![Screenshot 2021-08-27 114307](https://user-images.githubusercontent.com/53933493/131081000-cf52266f-90ec-4f7a-8418-de693d2af612.png)

Instead redirect to some google form or something.

**Comment by saswatsamal** [comment]
We have not enabled the "Join Us" button. We'll let you know when it is enabled.

**Comment by Saswat7101** [comment]
Okay okay no issues!
