### ISSUE TITLE
[ISSUE]: The responsiveness of the navbar of the website.

### ISSUE THREAD

**Issue by Abhijeet-Anand-01** [hackclubiter/hackclubiter.github.io#31]
**1. For laptop (< 1200px) and (> 990px) : Join Us button is collapsing**

**-> Solution** - There's a lot of space in the extreme left of the hack club icon. So by adjusting  it a bit, then the join us button will be back to its original shape

**2. For tablet (< 990px) and (> 767px) : Hack club icon disappeared**

**-> Solution** - I think it will be better to use the hamburger(3 dashes) from the tablet screen itself.

**3. For tablet (< 767px) : Hack club icon, Join us button, and Hamburger position is not in the right place.**

**-> Solution** - Keeping the UI in mind, I feel like it would be better if we keep the Hack club icon in the extreme left and  Join us and hamburger to the extreme right

I can work on the fix, I am open to the contribution. If you liked my solutions you can assign the issue to me.

Thanks!

**Comment by Saswat7101** [comment]
Ok cool!! You can work to fix this.

**Comment by saswatsamal** [comment]
> Ok cool!! You can work to fix this.

Nope. I'll review it once again.
Actually I've not pushed to main. So, once I do that, then I can allow this.

**Comment by Saswat7101** [comment]
Ohkay!

**Comment by Abhijeet-Anand-01** [comment]
> > Ok cool!! You can work to fix this.
> 
> Nope. I'll review it once again.
> Actually I've not pushed to main. So, once I do that, then I can allow this.

No Problem bhaiya!
If you required any contribution from my side then please let me know.
Thanks! 🍻

**Comment by saswatsamal** [comment]
> **1. For laptop (< 1200px) and (> 990px) : Join Us button is collapsing**
> 
> **-> Solution** - There's a lot of space in the extreme left of the hack club icon. So by adjusting it a bit, then the join us button will be back to its original shape
> 
> **2. For tablet (< 990px) and (> 767px) : Hack club icon disappeared**
> 
> **-> Solution** - I think it will be better to use the hamburger(3 dashes) from the tablet screen itself.
> 
> **3. For tablet (< 767px) : Hack club icon, Join us button, and Hamburger position is not in the right place.**
> 
> **-> Solution** - Keeping the UI in mind, I feel like it would be better if we keep the Hack club icon in the extreme left and Join us and hamburger to the extreme right
> 
> I can work on the fix, I am open to the contribution. If you liked my solutions you can assign the issue to me.
> 
> Thanks!

1. There's a lot of space becoz we are going to place the Hack Club's banner over there.
2. Second issue considered.
3. What do you mean by "not in right place"? As said, we will be placing the Hack Club Banner at the extreme left.

**Comment by Abhijeet-Anand-01** [comment]
1. Oh okay bhaiya then after that we can have a look into it!
2. Ok cool! Thanks!
3. I just mean to say these extract spaces are not looking so attractive

![IMG_20210906_122655](https://user-images.githubusercontent.com/64329744/132173819-d6884d7f-ecc7-475c-b80d-480dace4f979.jpg)

But considering the fact that you are going to add a banner, it's better to look into it afterward!
Thank you!

**Comment by Saswat7101** [comment]
Okay lets look into this after we insert the banners and all

**Comment by Abhijeet-Anand-01** [comment]
Yes that will be much better :)

**Comment by Saswat7101** [comment]
Also add saswat samal in the assignee
