### ISSUE TITLE
lottie-player size and position need to be fix for mobile view

### ISSUE THREAD

**Issue by Abhijeet-Anand-01** [hackclubiter/hackclubiter.github.io#32]
There are some extra space at the top and bottom of the lottie-player which is not looking so good according to me.

![issue2](https://user-images.githubusercontent.com/64329744/132138694-b0793a72-6065-482d-b9af-b5272879cc98.jpg)

**Here is a simple fix for it -**

In the media query section ,
just change top and width from -

_@media screen and (max-width: 32em)
.homebg-animation {
top: 0;
width: 122%;
}_

**to** 

_@media screen and (max-width: 32em)
.homebg-animation {
top: -30px;
width: 130%
}_

**And you will get the desired result -** 

![fixed](https://user-images.githubusercontent.com/64329744/132138699-ca7bd15f-16f1-497f-bee1-d3a2ae80a858.JPG)

Hope so it will be helpful.
Thank you!

**Comment by saswatsamal** [comment]
Cool! That's nice.
You can create a PR adding your changes.
Make sure that you are synced with the main branch.

**Comment by Abhijeet-Anand-01** [comment]
Okay bhaiya! 
I'm on it!
The PR will be directly to the main branch, right?

**Comment by saswatsamal** [comment]
> Okay bhaiya! 
> I'm on it!
> The PR will be directly to the main branch, right?

Make it a diff branch. We'll deploy it and see. If everything works fine then we'll merge it. :)

**Comment by Abhijeet-Anand-01** [comment]
Okay bhaiya! I'll do that.
Thanks!

**Comment by Abhijeet-Anand-01** [comment]
I've created a PR into the **codeupdate-main**.
Please let me know if any issues found.
Thanks!

**Comment by saswatsamal** [comment]
Merged! 🚀
