### ISSUE TITLE
[ISSUE] Alignment of Join Us for Mobile

### ISSUE THREAD

**Issue by theankitdash** [hackclubiter/hackclubiter.github.io#35]
![Join us (issue)](https://user-images.githubusercontent.com/53533461/132164152-d5d2addf-2f8b-4f64-a434-fea9361f37a5.jpg)
When the webiste is opened in a mobile, the alignmemt of 'Join Us' phrase is not in the middle of the box

**Comment by saswatsamal** [comment]
I see. I'll work on it.

**Comment by SamarjeetBanik** [comment]
I am working on it.
