### ISSUE TITLE
[ISSUE] UI laggy

### ISSUE THREAD

**Issue by theankitdash** [hackclubiter/hackclubiter.github.io#36]
UI is little laggy in the browser while scrolling up and down. It looks like the site is little heavy.

**Comment by saswatsamal** [comment]
![image](https://user-images.githubusercontent.com/39031660/132200834-90360bc7-ea45-4281-9354-3003ce19228c.png)
 I can see that the performance is nice. But yes, it's laggy because of the Lottie files animation. We will work on it. Maybe we can upload the Gif of the same.
