### ISSUE TITLE
[ISSUE] The join now link in the toast is redirecting to different page

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/hackclubiter.github.io#37]
When you click in the join now link in the toast it is redirecting to a 404 error page.

![image](https://user-images.githubusercontent.com/53933493/132175515-b1060f8e-a7c0-431e-994c-3f92ab8efbc2.png)

I think you have linked the wrong page or something. Have a look into this

**Comment by saswatsamal** [comment]
Fixed! :)
