### ISSUE TITLE
Content in the about page 

### ISSUE THREAD

**Issue by Nupur-Srivastava** [hackclubiter/hackclubiter.github.io#38]
There repeating of content in the about page

In the intro page the content are repeated.
The Intro part is the content all most same 
The content could be more sorted
![Screenshot (200)](https://user-images.githubusercontent.com/70944857/132251940-23eed11a-28be-4c39-af01-e32190bc39ca.png)
![Screenshot (201)](https://user-images.githubusercontent.com/70944857/132251943-b9cba5a7-3a93-4f27-9635-e63535d12cbb.png)

**Comment by Saswat7101** [comment]
Actually, we wanted to give something like a tagline or motto of our community on the landing page, but we didn't have any, so we managed with what we had. You can suggest something if you have something in mind to make it more attractive then you can suggest it here
