### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by apurv0207** [hackclubiter/hackclubiter.github.io#42]
I think, with due respects Its only a suggestion , I think our site has more plain and more deep colors than tacky colours like reds ,blues.. thank you.

**Comment by Saswat7101** [comment]
Ok, then what's your suggestion? Can you explain a little

**Comment by apurv0207** [comment]
hey Saswat,
I am just saying that the colour of the theme is too bright colours like
red , saffron can we change it to grey and its shades more blacks like
these.
. it's just a suggestion.
thanking you.

**Comment by saswatsamal** [comment]
The whole theme is based on @hackclub's theme so it's better to maintain. You can suggest the colors a/to Hack Club's theme. Thanks :)

**Comment by apurv0207** [comment]
Ohh, then sorry. I don't know about this protocol.
