### ISSUE TITLE
[FEATURE] Hover effects to the buttons and  nav bar contents.

### ISSUE THREAD

**Issue by MannyP31** [hackclubiter/hackclubiter.github.io#45]
<img width="956" alt="Screenshot (178)" src="https://user-images.githubusercontent.com/76945004/132991793-cdcfbeca-f799-4e0f-999e-c32eae372af7.png">

**Comment by Saswat7101** [comment]
The navbar items are linked to the appropriate section/page. Only hover effect need to be added

**Comment by MannyP31** [comment]
Yes exactly I mean to say that . We just need to work on the hover effect!!✌

**Comment by Saswat7101** [comment]
This issue is already raised. Check issue #29
