### ISSUE TITLE
[FEATURE] Navigation Tab --> Team

### ISSUE THREAD

**Issue by TiwariSimona** [hackclubiter/hackclubiter.github.io#50]
In the **navigation bar**, while clicking on the team option its showing 404page error. After refreshing so many times and opening it in different tabs its coming which is irritating. 
And also a suggestion, there is only mentioned main team, rest other team members can also be mentioned.
And instead of just name and photo of the person, their github and linkedIn profile links can also be displayed.

**Comment by Saswat7101** [comment]
We'll fix the team link in nav bar and we are working on the teams page's cards

**Comment by Saswat7101** [comment]
The issue with the link in the navbar has been fixed.

and the work is in progress about mentioning the rest of the team in the page
