### ISSUE TITLE
[ADD] Mail Link in Code of Conduct Page

### ISSUE THREAD

**Issue by arpanaditya** [hackclubiter/hackclubiter.github.io#53]
In the code of conduct section of [Hack Club](https://iter.hackclub.com/code-of-conduct) main website, the link (mailto) is not added in the mail id of hack club ITER.

I want to fix this issue... Assign this to me @Saswat7101 @saswatsamal

**Comment by Saswat7101** [comment]
![image](https://user-images.githubusercontent.com/53933493/133817613-36dfc688-b784-4605-be57-6def0f3b78f5.png)

as you can see (mailto) is already added.  Nothing to fix!!
