### ISSUE TITLE
[ISSUE] Join us button in navbar is unresponsive in the TEAM page

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/hackclubiter.github.io#56]
The join us button is unresponsive in the mobile view.

![image](https://user-images.githubusercontent.com/53933493/133816446-207fae6b-5c7d-4038-a7ef-2c7d02606333.png)

You can either make the button responsive or make the whole navbar a dropdown menu i.e. the Join us button will also be in the dropdown menu

**Comment by Sanjana-027** [comment]
@saswatsamal Bhaiya I have already fix it.
