### ISSUE TITLE
[ISSUE] Navbar

### ISSUE THREAD

**Issue by Sanjana-027** [hackclubiter/hackclubiter.github.io#62]
Hello,
When we click on **About, Team & Contact Section** the Navbar font-weight look  like below image :-

![WhatsApp Image 2021-10-03 at 8 14 44 PM](https://user-images.githubusercontent.com/79395290/135759164-83861aca-bdd5-4946-9537-b950c446640b.jpeg)

but as well as, when we click on **Workshops & Project Section** the Navbar font-weight look like below img :-

![img](https://user-images.githubusercontent.com/79395290/135759463-03478488-7e35-4420-8ed9-0156cab933ce.jpeg)

I will like to fix this **ISSUE** making all font-weight a uniform one.

Thanks!

**Comment by Sanjana-027** [comment]
Can I work on it ?

**Comment by saswatsamal** [comment]
Assigned.

**Comment by Sanjana-027** [comment]
Thanks!

**Comment by saswatsamal** [comment]
Fixed #63
