### ISSUE TITLE
[ISSUE] Cards are not aligned in the teams page

### ISSUE THREAD

**Issue by Saswat7101** [hackclubiter/hackclubiter.github.io#66]
I have just updated the team's page with the details of the core team members. But there is an issue with the cards not being properly aligned. 

![image](https://user-images.githubusercontent.com/53933493/136596597-0cab7745-8869-431f-bb08-351356ee7ec5.png)

In the image, it can be clearly seen that the card having details of "Payal Das" is not aligned with the cards from above and below it.

And also the spacing between the cards is too much I feel.

**Comment by saswatsamal** [comment]
Fixed #67
