### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Anosh21** [hackclubiter/hackclubiter.github.io#69]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saswatsamal** [comment]
Hey @Anosh21 
Which feature do you want to add? Please mention.

**Comment by Saswat7101** [comment]
This is the template for feature request that you have added. You need to add the details of the what feature you want us to add.

**Comment by Anosh21** [comment]
Add a Api

**Comment by saswatsamal** [comment]
Which API?

**Comment by Saswat7101** [comment]
What API to add?

**Comment by saswatsamal** [comment]
Since no response, I'm closing this issue.
